<a href="https://colab.research.google.com/github/EwenCheung/Learn-MachineLearning/blob/main/00_pytorch_fundamentals_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating tensors
use `torch.tensor()` to create tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0,1]

tensor([3, 6, 9])

### Random tensors

Why random tensors ?

Random tensors are important becasue the way many neural network learn is that they start with tensors full of random numbers and then adjust thouse random numbers to better represent the data.

`Start woth random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
### Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3029, 0.7919, 0.6095, 0.7064],
        [0.7381, 0.9817, 0.2384, 0.8190],
        [0.4136, 0.8574, 0.1029, 0.8070]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor with simiar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height,width,colour channels(R,G,B)
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

 ### Zeros and Ones

In [22]:
# Creates a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [27]:
# Use torch.range() # use arange (same with range but newer)

one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

Note 3 bug common error in Pytorch.

1. Tensors not right datatype - can use `tensor.dtype`
2. Tensors not right shape - can use `tensor.shape`
3. Tensors not on the right device - can use `tensor.device`


In [29]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= torch.float32, #datatype: float32,float16 ,int32 etc
                               device = "cpu", # cpu, cuda
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
# Float 16 tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
test = float_16_tensor*float_32_tensor
test.dtype

torch.float32

In [33]:
# Int 32 tensor

int_32_tensor = torch.tensor([3,6,9],
                             dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors ( Tensor Attribute )

In [34]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4285, 0.6301, 0.0676, 0.6983],
        [0.4020, 0.2913, 0.1331, 0.8756],
        [0.6660, 0.8987, 0.3278, 0.0778]])

In [35]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4285, 0.6301, 0.0676, 0.6983],
        [0.4020, 0.2913, 0.1331, 0.8756],
        [0.6660, 0.8987, 0.3278, 0.0778]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)

Tensor operation include:
* Addition
* Substraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add to it

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [37]:
tensor-10

tensor([-9, -8, -7])

In [38]:
tensor*10

tensor([10, 20, 30])

In [39]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [40]:
# pytorch built in function
torch.mul(tensor,10) # multiply by 10 for every element in tensor

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learning:

1. Element-wise multiplication 2 * [[1,2],[3,5]]
2. Matrix multiplication [[1,2],[3,5]]*[[1,2],[3,5]] (normal method)

In [42]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [43]:
# Matrix multiplication

torch.matmul(tensor,tensor)


tensor(14)

In [44]:
test = torch.rand(3,4)
test2 = torch.rand(4,5)
torch.matmul(test,test2)

tensor([[1.1412, 0.6317, 0.2717, 1.0564, 0.7526],
        [1.2208, 0.9117, 0.4639, 0.9701, 0.7378],
        [1.6164, 0.8937, 0.5825, 1.2923, 1.2330]])

In [45]:
### one of the common error is shape error

In [46]:
tensor = torch.rand(2,3)
tensor

tensor([[0.3847, 0.9098, 0.6900],
        [0.2102, 0.5397, 0.7606]])

In [47]:
tensor.T

tensor([[0.3847, 0.2102],
        [0.9098, 0.5397],
        [0.6900, 0.7606]])

## Finding the min, max, mean, sum, etc ( tensor aggregation )

In [48]:
# Create a tensor
x = torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [51]:
# Find the mean
torch.mean(x,dtype= torch.float32)

tensor(46.)

In [52]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [54]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
x.argmin() # Find the position of the minimum value

tensor(0)

In [56]:
x[0] # get what is in index 0

tensor(1)

In [57]:
x.argmax()

tensor(9)

In [58]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [59]:
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [62]:
# Change the view
z = x.view(1,9) # change z will change x , because they share the same memory
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
z[:,0]=5
z , x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
# Stack tensors on top of each other.
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [65]:
# torch.squeeze() - remove all single dimension

x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
x_squeezed = x_reshaped.squeeze()
x_squeezed , x_squeezed.shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [67]:
# unsqueeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed , x_unsqueezed.shape

(tensor([[[5., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [68]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [69]:
y = x.unsqueeze(dim=-1)
y, y.shape

(tensor([[[1],
          [2],
          [3]],
 
         [[4],
          [5],
          [6]]]),
 torch.Size([2, 3, 1]))

In [70]:
# permute() , change index for the matrix
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [71]:
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])

In [72]:
# Example:

x_ori = torch.rand(size = (224,224,3)) # height, weight, colour_channels
print(x_ori.shape)

# Permute to colour channel, height, weight( rearrange the axis)
x_permuted = x_ori.permute(2,0,1)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


##Indexing ( selecting data from tensors)

indexing with PyTorch similar to NumPy

In [73]:
x = torch.arange(1,19).reshape(2,3,3)
x , x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
x[0][1], x[0,1] # both is same

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [76]:
x[0][2][1] , x[0,2,1]

(tensor(8), tensor(8))

In [77]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [78]:
# can use : to select all dimension
x[:][0] , x[:,0] # different

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[ 1,  2,  3],
         [10, 11, 12]]))

In [79]:
x[:,1,2]

tensor([ 6, 15])

In [80]:
x[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

## PyTorch tensors & Numpy

* Data in NumPy want in PyTorch tensors `torch.from_numpy(ndarray)`

* Pytorch tensors -> Numpy `torch.Tensor.numpy()`

In [81]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # can .type(torch.float32). cause np is float 64 if need convert
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility ( trying to take random out of random )

in short how a neural network learns:

`start with random number-> tensor operation-> update random number-> again-> again-> achive the final`

To reduce the randomness in neural network. We use random.seed()

In [83]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A, random_tensor_B
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
# Set seed and try

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [85]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU ( making faster computation )

##1. Getting a GPU

1. Easiest - Use Google Colab
2. Your Own GPU
3. Use Cloud Computing - GCP, AWS, Azure

In [86]:
!nvidia-smi

Thu Jan  2 13:33:40 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. Check for GPU access with PyTorch

In [87]:
import torch
torch.cuda.is_available()

True

In [88]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [89]:
# Count number of device
torch.cuda.device_count()

1

## Putting tensors ( and models ) on the GPU

In [90]:
# Create a tensor ( default on the CPU )
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [93]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [94]:
# Moving tensors back to the CPU
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [106]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])